# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BitcoinHunt' do
pod 'SIOSocket', '~> 0.2.0'
pod "CloudSight", "~> 1.0"
pod 'AFNetworking', '~> 2.0'
end

target 'BitcoinHuntTests' do

end

target 'BitcoinHuntUITests' do

end

