# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GeotaggingBitcoin' do
pod "coinbase-official"
pod "CloudSight", "~> 1.0"
pod 'AFNetworking', '~> 2.0'

end



